GCMD::ACTION moveForward(CLIENTINFO * pClientInfo);
GCMD::ACTION moveLeft(CLIENTINFO * pClientInfo);
GCMD::ACTION moveRight(CLIENTINFO * pClientInfo);
GCMD::ACTION moveBack(CLIENTINFO * pClientInfo);
GCMD::ACTION setPowerFull(CLIENTINFO * pClientInfo);
GCMD::ACTION setPowerHalf(CLIENTINFO * pClientInfo);
GCMD::ACTION ComposeHTMLPostPINS(CLIENTINFO * pClientInfo);
GCMD::ACTION moveCommand(CLIENTINFO * pClientInfo);
GCMD::ACTION ComposeHTTP200(CLIENTINFO * pClientInfo);
void processPostData(char* postData);
void run(int loops);
